/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const perfomance: string;
export const perfomanceNumber: string;
export const perfomanceDescription: string;
