/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const bigScreenImage: string;
export const smallScreenImage: string;
export const block: string;
export const alternateBlock: string;
export const body: string;
