/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const component: string;
export const tweet: string;
export const user: string;
export const name: string;
