/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const SCSliderProvider: string;
export const scSliderProvider: string;
export const SCSliderWrapper: string;
export const scSliderWrapper: string;
export const SCSlider: string;
export const scSlider: string;
export const SCControlWrapper: string;
export const scControlWrapper: string;
export const SCControl: string;
export const scControl: string;
export const SCProgressFraction: string;
export const scProgressFraction: string;
export const SCPagerWrapper: string;
export const scPagerWrapper: string;
export const SCPagerElement: string;
export const scPagerElement: string;
