/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const sliderProvider: string;
export const sliderWrapper: string;
export const SCSlider: string;
export const scSlider: string;
export const card: string;
export const SCControlWrapper: string;
export const scControlWrapper: string;
export const SCControl: string;
export const scControl: string;
export const SCProgressFraction: string;
export const scProgressFraction: string;
export const SCPagerElement: string;
export const scPagerElement: string;
export const left: string;
export const right: string;
