/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const revealCard: string;
export const flip: string;
export const visible: string;
export const seen: string;
export const revealCardWrapper: string;
export const revealCardContent: string;
export const clientPromoLogo: string;
export const cardAlignment: string;
