/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const component: string;
export const bgImg: string;
export const anchor: string;
export const clientLogo: string;
export const overlay: string;
export const button: string;
