language: node_js
node_js:
    - "lts/*"
cache:
    directories:
        - public
        - .cache
        - node_modules

addons:
    chrome: stable # make sure to have Chrome available
before_install:
    - yarn global add @lhci/cli@0.3.x # install LHCI
script:
    - yarn test-ci
    - yarn build
    - lhci autorun
