version: 0.2

env:
    variables:
        BUILD_KEY: $(echo $CODEBUILD_SOURCE_VERSION | tr / -)
#parameter-store:
# key: "value"
# key: "value"

phases:
    install:
        commands:
            - curl -s "https://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=co" > ~/.mime.types
            - npm i -g yarn
            - yarn
            # - command
        #finally:
        # - command
        # - command
    pre_build:
        commands:
            # - yarn test --ci
            # - command
        #finally:
        # - command
        # - command
    build:
        commands:
            - echo $(BUILD_KEY)
            - yarn build && aws s3 sync --delete public "s3://$($ARTIFACT_BUCKET)/public/$(BUILD_KEY)"
        #finally:
        # - command
        # - command
    #post_build:
    #commands:
    # - command
    # - command
    #finally:
    # - command
    # - command
# artifacts:
#     files:
#         - "**/*"
#     base-directory: public
#     name: $(echo $CODEBUILD_SOURCE_VERSION | tr / -)
# - location
# - name
#discard-paths: yes
#base-directory: location
cache:
    paths:
        - node_modules/**/*
        - public/**/*
        - /usr/local/lib/node_modules/**/*
