version: 0.2

# env:
#     variables:
#parameter-store:
# key: "value"
# key: "value"

phases:
    install:
        commands:
            - curl -s -o mime.types "https://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=co"
            - sudo mv mime.types /etc/
            - npm i -g yarn
            - yarn
            # - command
        #finally:
        # - command
        # - command
    pre_build:
        commands:
            # - yarn test --ci
            # - command
        #finally:
        # - command
        # - command
    build:
        commands:
            - yarn build && aws s3 sync --no-progress --delete public "s3://aerian-site-preview-us-east-1/public/$(echo $CODEBUILD_WEBHOOK_TRIGGER | tr / -)"

cache:
    paths:
        - node_modules/**/*
        - public/**/*
        - /usr/local/lib/node_modules/**/*
