/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const component: string;
export const grid1: string;
export const grid2: string;
export const grid3: string;
export const grid4: string;
