/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const component: string;
export const growHeightIn: string;
export const funny: string;
export const details: string;
export const role: string;
export const skils: string;
export const fadePop: string;
