/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const heroBlock: string;
export const placeholder: string;
export const heroMedia: string;
export const heroContent: string;
