/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const component: string;
export const alternate: string;
export const arrow: string;
export const icon: string;
