/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const carouselWrapper: string;
export const component: string;
export const card: string;
export const carouselControl: string;
export const left: string;
export const right: string;
