/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const component: string;
export const section: string;
export const firstSection: string;
export const secondSection: string;
export const largeTitle: string;
export const sectionContent: string;
