/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const pageNavBar: string;
export const contentWrapper: string;
export const sectionNav: string;
export const sectionNavWrapper: string;
export const sectionNavItem: string;
export const withSectionNav: string;
