/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const contactInfo: string;
export const address: string;
export const part: string;
export const orgName: string;
export const phoneNumber: string;
export const email: string;
export const addressSection: string;
