/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const contactInfo: string;
export const slideInRight: string;
export const addressWrapper: string;
export const white: string;
export const contactIcon: string;
export const address: string;
export const part: string;
export const orgName: string;
export const orgSectionName: string;
export const addressSection: string;
export const addressSectionIcon: string;
export const phoneNumber: string;
export const email: string;
