const path = require("path");
module.exports = (baseConfig, env, config) => {
    // Prefer Gatsby ES6 entrypoint (module) over commonjs (main) entrypoint
    config.resolve.mainFields = ["browser", "module", "main"];

    // setup to us typings for css modules
    config.module.rules.push({
        test: /\.scss$/,
        loaders: [
            "style-loader",
            {
                loader: "typings-for-css-modules-loader",
                options: {
                    modules: true,
                    camelCase: true,
                    banner: `/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.`,
                    namedExport: true,
                    silent: true,
                    importLoaders: 2,
                    localIdentName: "[path][name]__[local]--[hash:base64:5]"
                }
            },
            "sass-loader"
        ],
        include: path.resolve(__dirname, "../")
    });

    // setup to use ts-loader
    config.module.rules.push({
        test: /\.(js|jsx|ts|tsx)$/,
        use: [
            {
                loader: require.resolve("ts-loader"),
                options: {
                    transpileOnly: true
                }
            },
            require.resolve("react-docgen-typescript-loader")
        ]
    });
    config.module.rules[0] = {
        ...config.module.rules[0],
        // Transpile Gatsby module because Gatsby includes un-transpiled ES6 code.
        exclude: [/node_modules\/(?!(gatsby)\/)/],
        include: [
            // path.resolve(__dirname, "../node_modules/gatsby"),
            path.resolve(__dirname, "../src")
        ]
    };

    config.resolve.extensions.push(".ts", ".tsx");

    return config;
};
