// This file is automatically generated from your CSS. Any edits will be overwritten.
export const component: string;
export const quote: string;
export const testimonialText: string;
export const cite: string;
export const nameTitle: string;
export const name: string;
export const title: string;
export const blockquoteImage: string;
