/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const component: string;
export const quoteLeft: string;
export const testimonialText: string;
export const testimonialFooter: string;
export const name: string;
export const title: string;
export const blockquoteImage: string;
