/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const component: string;
export const logo: string;
export const nav: string;
export const navActive: string;
export const linkBase: string;
export const link: string;
export const activeLink: string;
