/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const staffDetailEnter: string;
export const staffDetailEnterActive: string;
export const staffDetailLeave: string;
export const staffDetailLeaveActive: string;
export const ___gatsby: string;
export const gatsby: string;
export const largeTitle: string;
export const fadePop: string;
export const growHeightIn: string;
