/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const layoutGrid: string;
export const blockFull: string;
export const button: string;
export const fadePop: string;
