/* tslint:disable */
// This file is automatically generated from your CSS. Any edits will be overwritten.
export const component: string;
export const infographicCount: string;
export const infographicTitle: string;
export const infographicImage: string;
export const infoGraphicHidden: string;
export const infoGraphicShown: string;
export const fadein: string;
